Repository canonical/canonicalwebteam.launchpad, pull requests merged in 2020-04, with the labels that each got.

#17 Ability to pass metadata to build_image
  CHANGES.txt
  canonicalwebteam/launchpad/models.py
  setup.py
Labels: Review: Code needed, Review: QA needed

#18 v0.4.0: Webhooks should always have secret
  CHANGES.txt
  canonicalwebteam/launchpad/models.py
  setup.py
  tests/test_launchpad.py
Labels: Review: Code +1, Review: QA +1

#19 Added auth_consumer in the constructor method
  CHANGES.txt
  canonicalwebteam/launchpad/models.py
  setup.py
  tests/test_launchpad.py
Labels: Review: Code +1

#21 Remove classic from image builder support
  CHANGES.txt
  canonicalwebteam/launchpad/models.py
  setup.py
Labels: Review: Code needed, Review: QA needed
